Cd(__DIR__);;
#include "Utilities/Net.HH"

#include "Utilities/NetLog"

#include "Utilities/NetQueue"

#include "Drivers/Run"

#include "Protocols/Ethernet"

#include "Protocols/ARP"
#include "Protocols/IPV4"
#include "Protocols/ICMP"

#include "Protocols/Sockets"

#include "Utilities/BST"
#include "Protocols/UDP/MakeUDP"
#include "Utilities/Ping"


#include "Protocols/DHCP"

#include "Utilities/NetHandler" // needs IPV4, UDP, ICMP
